version: "3.9"
services:
  postgres:
    image: postgres:17-alpine3.20
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  # optional to add pgadmin in development
  # pgadmin:
  #   image: dpage/pgadmin4:8.5
  #   restart: always
  #   ports:
  #     - "5050:5050"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./pgadmin-data:/var/lib/pgadmin
  #   depends_on:
  #     - postgres

volumes:
  postgres-data:
  # pgadmin-data:
