version: "3.9"
services:
  postgres:
    image: postgres:16-alpine3.19
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4:8.5
    restart: always
    ports:
      - "5050:5050"
    env_file:
      - .env
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
  api-service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["./wait-for-it.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
volumes:
  postgres_data:
  pgadmin_data:
