// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	Email   string    `json:"email"`
	Picture string    `json:"picture"`
}

type UserSession struct {
	ID        uuid.UUID `json:"id"`
	User      uuid.UUID `json:"user"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"createdAt"`
}
